name: "release"
on:
  push:
    branches:
      - native-app

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Rust (stable)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install app dependencies and build it
      run: npm install && npm run build

    - name: Release Tauri bundle
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: fullscreen-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "Fullscreen v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: true