name: "release"

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always
  cache_path: |
    src-tauri/target
    ~/.cargo
  cargo_manifest: src-tauri/Cargo.toml

jobs:
  tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Restore from cache
      uses: actions/cache@v2
      with:
        path: ${{ env.cache_path }}
        key: ${{ runner.os }}-publish-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install js dependencies
      run: npm install
      
    - name: Build app
      run: npm run build

    - name: Release Tauri bundle
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: fullscreen-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "Fullscreen v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: true