name: "test"

on: [pull_request]

env:
  CARGO_TERM_COLOR: always
  cache_path: |
    node_modules
    src-tauri/target
    ~/.cargo
  cargo_manifest: src-tauri/Cargo.toml

jobs:
  tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Restore from cache
      uses: actions/cache@v2
      with:
        path: ${{ env.cache_path }}
        key: ${{ runner.os }}-publish-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    - name: Install js dependencies
      run: npm install
      
    - name: Build app
      run: npm run build

    - name: Run Tauri action
      uses: tauri-apps/tauri-action@v0
      with:
        configPath: "src-tauri/tauri.conf.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}